name: CLI Runner

on:
  workflow_call:
    inputs:
      cli_command:
        required: true
        type: string
      schedule_title:
        required: true
        type: string
      color:
        required: true
        type: string

jobs:
  run-cli:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: true

      - name: Install Playwright browsers
        run: deno run -A npm:playwright-core install --with-deps

      - name: Run the CLI
        env:
          SCRAPBOX_SID: ${{ secrets.SCRAPBOX_SID }}
        run: deno task ${{ inputs.cli_command }}

      - name: Notify Discord
        uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: ${{ inputs.schedule_title }}
          description: "${{ inputs.schedule_title }} has been executed."
          color: ${{ inputs.color }}
          url: "https://scrapbox.io/katayama8000/"
          username: "Scrapbox Bot"

      - name: Add Issue to Backlog
        if: failure()
        uses: katayama8000/backlog-issue-creator@0.3.2
        with:
          backlog_domain: "tatsufumi.backlog.com"
          api_key: ${{ secrets.BACKLOG_API_KEY }}
          project_id: "665456"
          issue_type_id: "3529948"
          summary: "${{ inputs.schedule_title }} has failed"
          description: "${{ inputs.schedule_title }} has been executed and failed. Please check the Scrapbox page for details: https://scrapbox.io/katayama8000/"
          priority_id: "3"
