name: CLI Runner

on:
  workflow_call:
    inputs:
      cli_command:
        required: true
        type: string
      schedule_title:
        required: true
        type: string
      color:
        required: true
        type: string

jobs:
  run-cli:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Get Playwright Version
        id: playwright-version
        run: |
          VERSION_QUOTED=$(jq -r '.imports.playwright' deno.json | sed 's/npm:playwright@//')
          echo "PLAYWRIGHT_VERSION=$VERSION_QUOTED" >> $GITHUB_ENV

      - name: Cache Deno dependencies
        uses: actions/cache@v4
        with:
          path: ~/.deno/deps
          key: ${{ runner.os }}-deno-${{ hashFiles('deno.lock') }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Restore Playwright Cache
        uses: actions/cache/restore@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Run the CLI
        env:
          SCRAPBOX_SID: ${{ secrets.SCRAPBOX_SID }}
        run: |
          # if cache is not hit (browser does not exist), install it
          if [ "${{ steps.playwright-cache.outputs.cache-hit }}" != "true" ]; then
            deno run -A npm:playwright-core install --with-deps
          fi
          # run the command
          deno task ${{ inputs.cli_command }}

      - name: Save Playwright Cache
        uses: actions/cache/save@v4
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

      - name: Notify Discord
        uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: ${{ inputs.schedule_title }}
          description: "${{ inputs.schedule_title }} has been executed."
          color: ${{ inputs.color }}
          url: "https://scrapbox.io/katayama8000/"
          username: "Scrapbox Bot"

      - name: Add Issue to Backlog
        if: failure()
        uses: katayama8000/backlog-issue-creator@0.3.2
        with:
          backlog_domain: "tatsufumi.backlog.com"
          api_key: ${{ secrets.BACKLOG_API_KEY }}
          project_id: "665456"
          issue_type_id: "3529948"
          summary: "${{ inputs.schedule_title }} has failed"
          description: "${{ inputs.schedule_title }} has been executed and failed. Please check the Scrapbox page for details: https://scrapbox.io/katayama8000/"
          priority_id: "3"
