name: Daily CLI

on:
  schedule:
    # every day except Sunday at 9:00 JST (01:00 UTC)
    - cron: "0 0 * * 1-6"
  workflow_dispatch:

jobs:
  call-reusable:
    uses: ./.github/workflows/cli_runner.yml
    with:
      cli_command: daily
      schedule_title: "Daily CLI"
      color: "#FF0000"
    secrets: inherit
