name: Daily CLI

on:
  schedule:
    # Runs daily at 10:00 JST (01:00 UTC)
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  call-cli-runner:
    uses: ./.github/workflows/cli-runner.yml
    with:
      cli_type: "daily"