name: Daily CLI

on:
  schedule:
    # Runs daily at 10:00 JST (01:00 UTC)
    - cron: '0 1 * * *'

jobs:
  run-daily-cli:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4

    - name: Install dependencies
      run: yarn install

    - name: Run daily task
      run: yarn daily
