name: Weekly CLI

on:
  schedule:
    # every Sunday at 11:00 JST (02:00 UTC)
    - cron: '0 2 * * 0'
  workflow_dispatch:

jobs:
  call-reusable:
    uses: ./.github/workflows/cli_runner.yml
    with:
      cli_command: weekly
      schedule_title: "Weekly CLI"
      color: "0x0000ff"
