name: Weekly CLI

on:
  schedule:
    # Runs every Sunday at 11:00 JST (02:00 UTC)
    - cron: '0 2 * * 0'
  workflow_dispatch:

jobs:
  call-cli-runner:
    uses: ./.github/workflows/cli-runner.yml
    with:
      cli_type: "weekly"