name: Weekly CLI

on:
  schedule:
    # Runs every Sunday at 11:00 JST (02:00 UTC)
    - cron: '0 2 * * 0'
  workflow_dispatch:

jobs:
  run-weekly-cli:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Run the CLI
      env:
        SCRAPBOX_SID: ${{ secrets.SCRAPBOX_SID }}
      run: yarn weekly

    - name: notify to discord
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        status: ${{ job.status }}
        title: "Weekly CLI"
        description: "Weekly CLI has been executed."
        color: 0x0000ff
        url: "https://github.com/katayama8000/scrapbox-cli"
        username: Scrapbox
