name: Weekly CLI

on:
  schedule:
    # Runs every Sunday at 10:00 JST (01:00 UTC)
    - cron: '0 1 * * 0'
  workflow_dispatch:

jobs:
  run-weekly-cli:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Run the CLI
      env:
        SCRAPBOX_SID: ${{ secrets.SCRAPBOX_SID }}
      run: yarn weekly
