name: Weekly CLI

on:
  schedule:
    # every Sunday at 10:00 JST (02:00 UTC)
    - cron: '0 1 * * 0'
  workflow_dispatch:

jobs:
  call-reusable:
    uses: ./.github/workflows/cli_runner.yml
    with:
      cli_command: weekly
      schedule_title: 'Weekly CLI'
      color: '#FF0000'
    secrets: inherit
